'use client'

/**
 * ExplanationRenderer
 *
 * Three-block layout for STEM (matches screenshot spec):
 *   Block 1 — Concept intro card (prose + centred formula)
 *   Block 2 — Variable definitions (bulleted list)
 *   Block 3 — Numbered steps (blue circle + title + working lines)
 *
 * Clean paragraph layout for non-STEM subjects.
 *
 * Parses the flat text format generated by the AI prompt:
 *   "Intro sentence.\nKey Formula: d = v*t/2\nv = ...\nStep 1: ...\n[working]\nAnswer: ..."
 *
 * DEBUG: open browser console → look for [ER] logs to confirm data is arriving.
 * If explanation is "" or null → the question has no explanation in DB.
 */

import { useState } from 'react'
import MathRenderer, { plainToLatex } from '@/components/ui/MathRenderer'
import { cn }       from '@/lib/utils'

// ── Pre-process a math working line ───────────────────────────────────────
// Converts plain-text working lines (e.g. "d = 250*3.5/2") to $...$
// so MathRenderer renders them as proper KaTeX.
// Called on working lines in STEM steps only.
function preprocessMath(text) {
  if (!text || text.includes('$')) return text  // already has delimiters
  const converted = plainToLatex(text)
  // Only wrap in $...$ if something actually changed
  if (converted !== text) return `$${converted}$`
  return text
}

// ── Subject classification ─────────────────────────────────────────────────
const STEM_SET = new Set([
  'mathematics', 'further mathematics', 'further_mathematics', 'further maths',
  'maths', 'math', 'physics', 'chemistry', 'statistics', 'biology',
  'computer science', 'computer_science',
])

function isStem(subject = '') {
  const s = subject.toLowerCase().replace(/_/g, ' ').trim()
  return STEM_SET.has(s) || /math|physic|chem|statistic|biol|comput/.test(s)
}

// ── Normalise raw text → array of lines ───────────────────────────────────
function toLines(raw, stem = false) {
  if (!raw?.trim()) return []

  const text = raw
    .replace(/\\n/g, '\n')
    .replace(/\r\n/g, '\n')
    .trim()

  // Try real newlines first
  const byNewline = text.split('\n').map((l) => l.trim()).filter(Boolean)
  if (byNewline.length > 1) return byNewline

  // Single string — no newlines at all (the DB stored everything in one line).
  // Split on Step N: / Answer: / Key Formula: / Remember: boundaries.
  const single = byNewline[0] ?? text
  const byMarker = single
    .split(/(?=\bStep\s+\d+[:.]\s|\bAnswer\s*:|\bKey\s+Formula\s*:|\bKey\s+Concept\s*:|\bRemember\s*:|💡)/i)
    .map((s) => s.trim())
    .filter(Boolean)
  if (byMarker.length > 1) return byMarker

  // STEM sentence-boundary fallback
  if (stem) {
    const bySentence = single
      .split(/(?<=\.)\s{2,}|(?<=\.)\s+(?=[A-Z])/)
      .map((s) => s.trim())
      .filter(Boolean)
    if (bySentence.length > 1) return bySentence
  }

  return [single]
}

// ── Parse flat lines → structured STEM blocks ──────────────────────────────
function parseStem(lines) {
  const result = {
    formula:   null,   // "Key Formula: ..." → extracted formula text
    variables: [],     // variable definition lines
    prose:     [],     // intro text before first step
    steps:     [],     // [{ num, title, working: [{isAnswer, text}] }]
    answer:    null,   // standalone "Answer: ..."
    remember:  null,   // "Remember: ..." or "💡 ..."
  }

  let cur        = null   // current step being built
  let seenStep   = false

  for (const line of lines) {
    // Key Formula
    if (/^(?:key\s+formula|formula(?:\s+used)?)\s*:/i.test(line)) {
      result.formula = line.replace(/^[^:]+:\s*/i, '').trim()
      continue
    }

    // Answer
    if (/^answer\s*:/i.test(line)) {
      const text = line.replace(/^answer\s*:\s*/i, '').trim()
      result.answer = text
      cur?.working.push({ isAnswer: true, text })
      continue
    }

    // Remember / Key Concept
    if (/^(?:💡|remember(?:\s+this)?:|key\s+concept:)/i.test(line)) {
      result.remember = line.replace(/^(?:💡\s*)?(?:remember(?:\s+this)?:|key\s+concept:)\s*/i, '').trim()
      continue
    }

    // Step N: ...
    const stepM = line.match(/^step\s*(\d+)[:.]\s*(.*)/i)
              ?? line.match(/^(\d+)[.)]\s+(.+)/)
    if (stepM) {
      seenStep = true
      const fullTitle = stepM[2]?.trim() ?? ''

      // If the AI wrote the whole step as one narrative sentence, split it:
      // first sentence becomes the title, remaining sentences become working lines.
      // e.g. "Take the 4 out to get 4(4x^2 - 25). Now factor." → title + working
      const titleParts = fullTitle.split(/(?<=\.)\s+(?=[A-Z])/)
      const title      = titleParts[0]?.replace(/\.+$/, '').trim() ?? fullTitle
      const extra      = titleParts.slice(1).map((s) => s.trim()).filter(Boolean)

      cur = { num: parseInt(stepM[1], 10), title, working: [] }
      result.steps.push(cur)
      for (const e of extra) cur.working.push({ isAnswer: false, text: e })
      continue
    }

    // Variable definition (before steps): "x = ...", "v = speed of sound = 250 m/s"
    if (!seenStep && /^[a-zA-Z_]\w*\s*=/.test(line) && line.length < 120) {
      result.variables.push(line)
      continue
    }

    // Inside a step → working line
    if (cur) {
      cur.working.push({ isAnswer: false, text: line })
      continue
    }

    // Before any step → intro prose
    if (!seenStep) {
      result.prose.push(line)
    }
  }

  return result
}

// ── Hint reveal button ─────────────────────────────────────────────────────
function HintReveal({ hint }) {
  const [open, setOpen] = useState(false)
  if (!hint?.trim()) return null
  return open ? (
    <div className="flex items-start gap-2 bg-amber-light border border-amber/25 rounded-xl px-4 py-3">
      <span className="flex-shrink-0">💡</span>
      <p className="text-sm text-amber leading-relaxed flex-1">{hint}</p>
      <button onClick={() => setOpen(false)}
        className="text-amber/40 hover:text-amber text-xl leading-none ml-2 flex-shrink-0">×</button>
    </div>
  ) : (
    <button onClick={() => setOpen(true)}
      className="inline-flex items-center gap-1.5 text-xs font-bold text-amber bg-amber-light border border-amber/25 px-3 py-2 rounded-xl hover:bg-amber/20 transition-colors">
      💡 Show Hint
    </button>
  )
}

// ── Numbered blue circle ───────────────────────────────────────────────────
function StepNum({ n }) {
  return (
    <div className="flex-shrink-0 w-8 h-8 rounded-full bg-brand-500 text-white text-[14px] font-bold flex items-center justify-center shadow-sm mt-0.5">
      {n}
    </div>
  )
}

// ── STEM three-block renderer ──────────────────────────────────────────────
function STEMExplanation({ blocks, rawLines, hint, score, showClosing }) {
  const { formula, variables, prose, steps, answer, remember } = blocks

  const hasFormula = !!formula
  const hasProse   = prose.length > 0
  const hasVars    = variables.length > 0
  const hasSteps   = steps.length > 0

  // If no structured blocks at all, fall back to auto-numbering every line
  // Exclude answer/formula/remember and wrong-option lines (A. / B. / C. / D.)
  const fallbackLines = !hasSteps && !hasProse && !hasFormula
    ? rawLines.filter((l) =>
        !/^(?:answer|key\s+formula|remember|💡)/i.test(l) &&
        !/^[A-D][.)]\s/.test(l)
      )
    : []

  return (
    <div className="flex flex-col gap-0 rounded-2xl overflow-hidden border border-brand-200 bg-white">

      {/* ── Header ─────────────────────────────────────────────────────── */}
      <div className="bg-brand-900 px-5 py-3">
        <p className="text-xs font-bold uppercase tracking-widest text-white/60">📖 Solution</p>
      </div>

      <div className="px-5 py-5 flex flex-col gap-4">

        {/* Hint */}
        {hint?.trim() && <HintReveal hint={hint} />}

        {/* ── BLOCK 1: Concept introduction ──────────────────────────── */}
        {(hasProse || hasFormula) && (
          <div className="bg-[#f0f4ff] border border-[#c7d4f7] rounded-xl px-5 py-4 flex flex-col gap-3">
            {/* Prose intro */}
            {prose.map((line, i) => (
              <p key={i} className="text-sm text-ink-2 leading-relaxed">
                <MathRenderer text={line} />
              </p>
            ))}
            {/* Formula — centred, prominent */}
            {hasFormula && (
              <div className="flex justify-center mt-1">
                <div className="inline-block bg-white border border-brand-200 rounded-xl px-6 py-3 text-center shadow-sm min-w-[140px]">
                  <p className="text-[10px] font-bold uppercase tracking-widest text-brand-500 mb-2">
                    Formula
                  </p>
                  {/* Wrap in a div so KaTeX block-renders */}
                  <div className="flex justify-center text-base font-semibold text-brand-900">
                    <MathRenderer text={formula} />
                  </div>
                </div>
              </div>
            )}
          </div>
        )}

        {/* ── BLOCK 2: Variable definitions ──────────────────────────── */}
        {hasVars && (
          <div className="bg-[#edf8ed] border border-success/25 rounded-xl px-5 py-4 flex flex-col gap-2">
            <p className="text-[10px] font-bold uppercase tracking-widest text-success/70 mb-0.5">
              Where:
            </p>
            {variables.map((v, i) => (
              <div key={i} className="flex items-start gap-2.5">
                <span className="text-success font-bold mt-0.5 flex-shrink-0 text-base leading-none">•</span>
                <p className="text-sm text-ink leading-relaxed">
                  <MathRenderer text={preprocessMath(v)} />
                </p>
              </div>
            ))}
          </div>
        )}

        {/* ── BLOCK 3: Numbered calculation steps ────────────────────── */}
        {hasSteps && (
          <div className="flex flex-col gap-5">
            {steps.map((step) => (
              <div key={step.num} className="flex items-start gap-4">

                {/* Blue numbered circle — matches screenshot spec */}
                <StepNum n={step.num} />

                <div className="flex-1 min-w-0">
                  {/* Step title */}
                  {step.title && (
                    <p className="text-sm font-semibold text-ink mb-2.5 leading-snug">
                      <MathRenderer text={step.title} />
                    </p>
                  )}

                  {/* Working lines */}
                  {step.working.length > 0 && (
                    <div className="bg-[#f8f9fc] border border-brand-100 rounded-xl px-4 py-3 flex flex-col gap-1.5 overflow-x-auto">
                      {step.working.map((w, wi) =>
                        w.isAnswer ? (
                          /* Answer within step — visually distinct */
                          <div key={wi} className="flex items-center gap-2 pt-2 mt-1 border-t border-brand-100">
                            <span className="text-xs font-bold text-success flex-shrink-0">✓</span>
                            <span className="text-sm font-bold text-success">
                              <MathRenderer text={preprocessMath(w.text)} />
                            </span>
                          </div>
                        ) : (
                          <p key={wi} className="text-sm text-ink font-mono leading-relaxed whitespace-pre-wrap break-words">
                            <MathRenderer text={preprocessMath(w.text)} />
                          </p>
                        )
                      )}
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Fallback: plain lines auto-numbered when no structure detected */}
        {fallbackLines.length > 0 && (
          <div className="flex flex-col gap-4">
            {fallbackLines.map((line, i) => (
              <div key={i} className="flex items-start gap-4">
                <StepNum n={i + 1} />
                <p className="text-sm text-ink leading-relaxed flex-1 pt-0.5">
                  <MathRenderer text={preprocessMath(line)} />
                </p>
              </div>
            ))}
          </div>
        )}

        {/* Standalone answer (not inside any step) */}
        {answer && !hasSteps && (
          <div className="flex items-center gap-3 bg-success-light border border-success/30 rounded-xl px-4 py-3">
            <span className="text-xs font-bold text-success uppercase tracking-widest flex-shrink-0">✓ Answer</span>
            <span className="font-bold text-success text-sm">
              <MathRenderer text={answer} />
            </span>
          </div>
        )}

        {/* Remember callout */}
        {remember && (
          <div className="bg-amber-light/60 border border-amber/20 rounded-xl px-4 py-3">
            <p className="text-sm text-amber font-medium">
              💡 <strong>Remember:</strong>{' '}
              <MathRenderer text={remember} />
            </p>
          </div>
        )}

        {/* Encouragement */}
        {showClosing && score !== null && (
          <p className="text-xs text-ink-4 border-t border-brand-100 pt-2.5">
            {score >= 75
              ? '⭐ Great work — keep using this approach on similar questions.'
              : score >= 50
              ? '📚 Almost there — review these steps and it will click.'
              : "💪 Follow these steps carefully and you'll get it next time."}
          </p>
        )}

      </div>
    </div>
  )
}

// ── Non-STEM clean paragraph renderer ─────────────────────────────────────
function ConceptExplanation({ lines, hint, score, showClosing }) {
  const isRemember = (l) => /^(?:💡|remember(?:\s+this)?:|key\s+concept:)/i.test(l)
  const isWrong    = (l) => /^[A-D][.)]\s/.test(l)

  const proseLines   = lines.filter((l) => !isRemember(l) && !isWrong(l))
  const wrongLines   = lines.filter(isWrong)
  const rememberLine = lines.find(isRemember)

  const rememberText = rememberLine
    ?.replace(/^(?:💡\s*)?(?:remember(?:\s+this)?:|key\s+concept:)\s*/i, '') ?? ''

  return (
    <div className="rounded-2xl overflow-hidden border border-brand-200 bg-white">
      <div className="bg-brand-900 px-5 py-3">
        <p className="text-xs font-bold uppercase tracking-widest text-white/60">📖 Explanation</p>
      </div>

      <div className="px-5 py-4 flex flex-col gap-3">
        {hint?.trim() && <HintReveal hint={hint} />}

        {/* Prose — one paragraph per line */}
        {proseLines.length > 0 && (
          <div className="flex flex-col gap-2">
            {proseLines.map((line, i) => (
              <p key={i} className="text-sm text-brand-700 leading-relaxed">
                <MathRenderer text={line} />
              </p>
            ))}
          </div>
        )}

        {/* Why other options are wrong */}
        {wrongLines.length > 0 && (
          <div className="flex flex-col gap-1.5 pt-1">
            <p className="text-[10px] font-bold uppercase tracking-widest text-ink-4 mb-0.5">
              Why the other options are wrong
            </p>
            {wrongLines.map((line, i) => {
              const letter  = line.match(/^([A-D])/)?.[1] ?? ''
              const content = line.replace(/^[A-D][.)]\s*/, '')
              return (
                <div key={i}
                  className="flex items-start gap-2.5 bg-danger-light/30 border border-danger/10 rounded-xl px-4 py-2.5">
                  <span className="w-5 h-5 rounded-full bg-danger/10 text-danger text-[11px] font-bold flex items-center justify-center flex-shrink-0 mt-0.5">
                    {letter}
                  </span>
                  <p className="text-sm text-ink-2 leading-relaxed flex-1">
                    <MathRenderer text={content} />
                  </p>
                </div>
              )
            })}
          </div>
        )}

        {/* Remember */}
        {rememberText && (
          <div className="bg-amber-light/60 border border-amber/20 rounded-xl px-4 py-3">
            <p className="text-sm text-amber font-medium">
              💡 <strong>Remember:</strong> <MathRenderer text={rememberText} />
            </p>
          </div>
        )}

        {showClosing && score !== null && (
          <p className="text-xs text-ink-4 border-t border-brand-200 pt-2.5">
            {score >= 75
              ? "⭐ Well done — you've got this concept."
              : score >= 50
              ? "📚 You're on the right track — revisit this and it will stick."
              : "💪 Now you know — you'll recognise this much faster next time."}
          </p>
        )}
      </div>
    </div>
  )
}

// ── Main export ────────────────────────────────────────────────────────────
/**
 * Props:
 *   explanation  string — raw explanation text from DB
 *   hint         string — optional hint
 *   subject      string — e.g. "mathematics", "english_language"
 *   score        number — 0-100 optional
 *   showClosing  bool   — show encouragement line (default true)
 */
export default function ExplanationRenderer({
  explanation,
  hint,
  subject     = '',
  score       = null,
  showClosing = true,
  className   = '',
}) {
  // Debug log — remove once confirmed working
  if (typeof window !== 'undefined') {
    console.log('[ER]', subject, '|', explanation?.length ?? 0, 'chars |',
      JSON.stringify((explanation ?? '').slice(0, 100)))
  }

  if (!explanation?.trim() && !hint?.trim()) return null

  const stem  = isStem(subject)
  const lines = toLines(explanation ?? '', stem)

  if (!stem) {
    return (
      <div className={className}>
        <ConceptExplanation lines={lines} hint={hint} score={score} showClosing={showClosing} />
      </div>
    )
  }

  const blocks = parseStem(lines)

  return (
    <div className={className}>
      <STEMExplanation
        blocks={blocks}
        rawLines={lines}
        hint={hint}
        score={score}
        showClosing={showClosing}
      />
    </div>
  )
}