'use client'

/**
 * ExplanationRenderer
 *
 * Three-block layout for STEM (matches screenshot spec):
 *   Block 1 — Concept intro card (prose + centred formula)
 *   Block 2 — Variable definitions (bulleted list)
 *   Block 3 — Numbered steps (blue circle + title + working lines)
 *
 * Clean paragraph layout for non-STEM subjects.
 *
 * Parses the flat text format generated by the AI prompt.
 */

import { useState } from 'react'
import MathRenderer, { plainToLatex } from '@/components/ui/MathRenderer'
import { cn } from '@/lib/utils'

// ── Bold/italic markdown renderer ─────────────────────────────────────────
// Renders **bold** and *italic* inline markdown as React nodes.
// Passes math-only segments through MathRenderer unchanged.
export function renderBold(text) {
  if (!text) return null
  // Fast path — no markdown markers at all
  if (!text.includes('**') && !text.includes('*') && !text.includes('__')) {
    return <MathRenderer text={text} />
  }

  // Process ** bold ** — greedy match
  const parts = []
  let remaining = text
  const boldRe = /\*\*(.+?)\*\*/gs

  let lastIdx = 0
  let match

  while ((match = boldRe.exec(text)) !== null) {
    // Text before this bold segment
    if (match.index > lastIdx) {
      parts.push(
        <MathRenderer key={`t-${lastIdx}`} text={text.slice(lastIdx, match.index)} />
      )
    }
    // Bold segment
    parts.push(<strong key={`b-${match.index}`}>{match[1]}</strong>)
    lastIdx = match.index + match[0].length
  }

  // Remaining text after last bold marker
  if (lastIdx < text.length) {
    parts.push(<MathRenderer key={`t-end`} text={text.slice(lastIdx)} />)
  }

  return parts.length > 0 ? <>{parts}</> : <MathRenderer text={text} />
}

// ── Text joining fix ───────────────────────────────────────────────────────
// Ensures no two words run together after newline stripping.
function fixSpacing(text) {
  if (!text) return text
  return text
    .replace(/\r\n/g, ' ')        // Windows line endings → space
    .replace(/\r/g, ' ')          // Old Mac line endings → space
    .replace(/\\n/g, ' ')         // Escaped literal \n → space
    .replace(/\n/g, ' ')          // Unix line endings → space
    .replace(/([a-z])([A-Z])/g, '$1 $2')  // camelCase → spaced
    .replace(/ {2,}/g, ' ')       // multiple spaces → single
    .replace(/ ([.,;:!?])/g, '$1') // space before punctuation → removed
    .trim()
}

// ── Pre-process a math working line ───────────────────────────────────────
function preprocessMath(text) {
  if (!text || text.includes('$')) return text
  const converted = plainToLatex(text)
  if (converted !== text) return `$${converted}$`
  return text
}

// ── Subject classification ─────────────────────────────────────────────────
const STEM_SET = new Set([
  'mathematics', 'further mathematics', 'further_mathematics', 'further maths',
  'maths', 'math', 'physics', 'chemistry', 'statistics', 'biology',
  'computer science', 'computer_science',
])

function isStem(subject = '') {
  const s = subject.toLowerCase().replace(/_/g, ' ').trim()
  return STEM_SET.has(s) || /math|physic|chem|statistic|biol|comput/.test(s)
}

// ── Normalise raw text → array of lines ───────────────────────────────────
function toLines(raw, stem = false) {
  if (!raw?.trim()) return []

  const text = raw
    .replace(/\\n/g, '\n')
    .replace(/\r\n/g, '\n')
    .trim()

  // Try real newlines first
  const byNewline = text.split('\n').map((l) => l.trim()).filter(Boolean)
  if (byNewline.length > 1) return byNewline

  // Single string — no newlines at all (DB stored everything on one line).
  // Split on Step N: / Answer: / Key Formula: / Remember: / ✅ / 💡 boundaries.
  // IMPORTANT: add a space before the match so joining doesn't strip it.
  const single = byNewline[0] ?? text
  const byMarker = single
    .split(/\s*(?=\bStep\s+\d+[:.]\s|\bAnswer\s*:|\bKey\s+Formula\s*:|\bKey\s+Concept\s*:|\bRemember\s*:|✅|💡)/i)
    .map((s) => s.trim())
    .filter(Boolean)
  if (byMarker.length > 1) return byMarker

  // STEM sentence-boundary fallback
  if (stem) {
    const bySentence = single
      .split(/(?<=\.)\s{1,}|(?<=\?)\s{1,}/)
      .map((s) => s.trim())
      .filter(Boolean)
    if (bySentence.length > 1) return bySentence
  }

  return [single]
}

// ── Hint reveal component ──────────────────────────────────────────────────
function HintReveal({ hint }) {
  const [open, setOpen] = useState(false)
  return (
    <div>
      {!open ? (
        <button
          onClick={() => setOpen(true)}
          className="text-xs font-semibold text-amber flex items-center gap-1.5 hover:opacity-80 transition-opacity"
        >
          💡 Show hint
        </button>
      ) : (
        <div className="flex items-start gap-2 bg-amber-light/60 border border-amber/20 rounded-xl px-4 py-2.5">
          <span className="text-sm flex-shrink-0">💡</span>
          <p className="text-sm text-amber leading-relaxed flex-1">{hint}</p>
          <button onClick={() => setOpen(false)} className="text-amber/50 hover:text-amber text-lg leading-none flex-shrink-0">×</button>
        </div>
      )}
    </div>
  )
}

// ── STEM explanation parser ────────────────────────────────────────────────
function parseStem(lines) {
  const blocks = {
    intro:           [],
    formulaLine:     null,
    variables:       [],
    steps:           [],
    answerStatement: null,
    remember:        null,
  }

  let mode = 'intro'
  let currentStep = null

  for (const line of lines) {
    const lo = line.toLowerCase()

    if (/^(?:✅|the\s+answer\s+is\b)/i.test(line)) {
      blocks.answerStatement = line
      mode = 'after'
      continue
    }
    if (/^(?:💡|remember(?:\s+this)?:|key\s+concept:|remember:)/i.test(line)) {
      blocks.remember = line.replace(/^(?:💡\s*)?(?:remember(?:\s+this)?:|key\s+concept:)\s*/i, '').trim()
      mode = 'after'
      continue
    }

    const stepMatch = line.match(/^Step\s+(\d+)\s*[:.]\s*(.*)/i)
    if (stepMatch) {
      currentStep = { number: parseInt(stepMatch[1]), title: stepMatch[2], working: [] }
      blocks.steps.push(currentStep)
      mode = 'step'
      continue
    }

    if (/^(?:key\s+formula|formula)\s*:/i.test(line)) {
      blocks.formulaLine = line.replace(/^(?:key\s+formula|formula)\s*:\s*/i, '')
      mode = 'formula'
      continue
    }

    if (/^where\s*:/i.test(line) || (/^[a-zA-Z_]\s*=\s/.test(line) && mode !== 'step')) {
      blocks.variables.push(line)
      mode = 'variables'
      continue
    }

    if (mode === 'step' && currentStep) {
      currentStep.working.push({
        text: line,
        isMath: /[=÷×+\-*/^√%]/.test(line) || line.includes('$'),
        isAnswerStatement: /^(?:✅|the\s+answer\s+is\b)/i.test(line),
      })
    } else if (mode === 'intro') {
      blocks.intro.push(line)
    } else if (mode === 'variables') {
      blocks.variables.push(line)
    }
  }

  return blocks
}

// ── STEM explanation renderer ──────────────────────────────────────────────
function STEMExplanation({ blocks, rawLines, hint, score, showClosing }) {
  const remember = blocks.remember

  return (
    <div className="rounded-2xl overflow-hidden border border-brand-200 bg-white">
      <div className="bg-brand-900 px-5 py-3">
        <p className="text-xs font-bold uppercase tracking-widest text-white/60">📐 Step-by-step working</p>
      </div>

      <div className="px-5 py-4 flex flex-col gap-4">
        {hint?.trim() && <HintReveal hint={hint} />}

        {/* Intro */}
        {blocks.intro.length > 0 && (
          <div className="flex flex-col gap-1.5">
            {blocks.intro.map((line, i) => (
              <p key={i} className="text-sm text-brand-700 leading-relaxed">
                {renderBold(line)}
              </p>
            ))}
          </div>
        )}

        {/* Key formula */}
        {blocks.formulaLine && (
          <div className="bg-brand-50 border border-brand-100 rounded-xl px-5 py-3 text-center">
            <p className="text-xs font-bold uppercase tracking-widest text-brand-400 mb-2">Key Formula</p>
            <MathRenderer text={blocks.formulaLine} block />
          </div>
        )}

        {/* Variables */}
        {blocks.variables.length > 0 && (
          <div className="bg-surface border border-border rounded-xl px-4 py-3 flex flex-col gap-1">
            {blocks.variables.map((v, i) => (
              <p key={i} className="text-sm text-ink-2 leading-snug">
                <MathRenderer text={v} />
              </p>
            ))}
          </div>
        )}

        {/* Steps */}
        {blocks.steps.map((step, si) => (
          <div key={si} className="flex gap-3">
            <div className="w-7 h-7 rounded-full bg-brand-800 text-white text-xs font-bold flex items-center justify-center flex-shrink-0 mt-0.5">
              {step.number}
            </div>
            <div className="flex-1 min-w-0">
              {step.title && (
                <p className="text-sm font-semibold text-ink mb-1.5">
                  {renderBold(step.title)}
                </p>
              )}
              {step.working.map((w, wi) => {
                if (w.isAnswerStatement) {
                  return (
                    <p key={wi} className="text-sm font-bold text-success leading-relaxed mt-1">
                      {renderBold(w.text)}
                    </p>
                  )
                }
                return (
                  <p key={wi} className={cn(
                    'leading-snug',
                    w.isMath ? 'text-sm font-mono text-ink bg-surface px-2 py-1 rounded my-0.5 inline-block' : 'text-sm text-ink-2'
                  )}>
                    <MathRenderer text={w.isMath ? preprocessMath(w.text) : w.text} />
                  </p>
                )
              })}
            </div>
          </div>
        ))}

        {/* Fallback: no steps parsed — show raw lines */}
        {blocks.steps.length === 0 && blocks.intro.length === 0 && rawLines.length > 0 && (
          <div className="flex flex-col gap-2">
            {rawLines.map((line, i) => (
              <p key={i} className="text-sm text-brand-700 leading-relaxed">
                {renderBold(line)}
              </p>
            ))}
          </div>
        )}

        {/* ✅ Answer statement (if not already in a step) */}
        {blocks.answerStatement && !blocks.steps.some((s) => s.working.some((w) => w.isAnswerStatement)) && (
          <p className="text-sm font-bold text-success leading-relaxed pt-1">
            {renderBold(blocks.answerStatement)}
          </p>
        )}

        {/* Remember callout */}
        {remember && (
          <div className="bg-amber-light/60 border border-amber/20 rounded-xl px-4 py-3">
            <p className="text-sm text-amber font-medium">
              💡 <strong>Remember:</strong>{' '}
              <MathRenderer text={remember} />
            </p>
          </div>
        )}

        {/* Encouragement */}
        {showClosing && score !== null && (
          <p className="text-xs text-ink-4 border-t border-brand-100 pt-2.5">
            {score >= 75
              ? '⭐ Great work — keep using this approach on similar questions.'
              : score >= 50
              ? '📚 Almost there — review these steps and it will click.'
              : "💪 Follow these steps carefully and you'll get it next time."}
          </p>
        )}

      </div>
    </div>
  )
}

// ── Non-STEM clean paragraph renderer ─────────────────────────────────────
function ConceptExplanation({ lines, hint, score, showClosing }) {
  const isRemember        = (l) => /^(?:💡|remember(?:\s+this)?:|key\s+concept:)/i.test(l)
  const isWrong           = (l) => /^[A-D][.)]\s/.test(l)
  const isAnswerStatement = (l) => l.startsWith('✅')

  const proseLines    = lines.filter((l) => !isRemember(l) && !isWrong(l) && !isAnswerStatement(l))
  const wrongLines    = lines.filter(isWrong)
  const rememberLine  = lines.find(isRemember)
  const answerStatLine = lines.find(isAnswerStatement)

  const rememberText = rememberLine
    ?.replace(/^(?:💡\s*)?(?:remember(?:\s+this)?:|key\s+concept:)\s*/i, '') ?? ''

  return (
    <div className="rounded-2xl overflow-hidden border border-brand-200 bg-white">
      <div className="bg-brand-900 px-5 py-3">
        <p className="text-xs font-bold uppercase tracking-widest text-white/60">📖 Explanation</p>
      </div>

      <div className="px-5 py-4 flex flex-col gap-3">
        {hint?.trim() && <HintReveal hint={hint} />}

        {/* Prose — one paragraph per line */}
        {proseLines.length > 0 && (
          <div className="flex flex-col gap-2">
            {proseLines.map((line, i) => (
              <p key={i} className="text-sm text-brand-700 leading-relaxed">
                {renderBold(line)}
              </p>
            ))}
          </div>
        )}

        {/* Why other options are wrong */}
        {wrongLines.length > 0 && (
          <div className="flex flex-col gap-1.5 pt-1">
            <p className="text-[10px] font-bold uppercase tracking-widest text-ink-4 mb-0.5">
              Why the other options are wrong
            </p>
            {wrongLines.map((line, i) => {
              const letter  = line.match(/^([A-D])/)?.[1] ?? ''
              const content = line.replace(/^[A-D][.)]\s*/, '')
              return (
                <div key={i} className="flex items-start gap-2.5 bg-danger-light/30 border border-danger/10 rounded-xl px-4 py-2.5">
                  <span className="w-5 h-5 rounded-full bg-danger/10 text-danger text-[11px] font-bold flex items-center justify-center flex-shrink-0 mt-0.5">
                    {letter}
                  </span>
                  <p className="text-sm text-ink-2 leading-relaxed flex-1">
                    {renderBold(content)}
                  </p>
                </div>
              )
            })}
          </div>
        )}

        {/* ✅ Bold answer statement */}
        {answerStatLine && (
          <p className="text-sm font-bold text-success leading-relaxed pt-1">
            {renderBold(answerStatLine)}
          </p>
        )}

        {rememberText && (
          <div className="bg-amber-light/60 border border-amber/20 rounded-xl px-4 py-3">
            <p className="text-sm text-amber font-medium">
              💡 <strong>Remember:</strong> <MathRenderer text={rememberText} />
            </p>
          </div>
        )}

        {showClosing && score !== null && (
          <p className="text-xs text-ink-4 border-t border-brand-200 pt-2.5">
            {score >= 75
              ? "⭐ Well done — you've got this concept."
              : score >= 50
              ? "📚 You're on the right track — revisit this and it will stick."
              : "💪 Now you know — you'll recognise this much faster next time."}
          </p>
        )}
      </div>
    </div>
  )
}

// ── Main export ────────────────────────────────────────────────────────────
/**
 * Props:
 *   explanation  string — raw explanation text from DB
 *   hint         string — optional hint
 *   subject      string — e.g. "mathematics", "english_language"
 *   score        number — 0-100 optional
 *   showClosing  bool   — show encouragement line (default true)
 */
export default function ExplanationRenderer({
  explanation,
  hint,
  subject     = '',
  score       = null,
  showClosing = true,
  className   = '',
}) {
  if (!explanation?.trim() && !hint?.trim()) return null

  const stem  = isStem(subject)
  // Fix spacing before line parsing so joining artifacts are cleaned
  const clean = explanation
    ? explanation.replace(/\\n/g, '\n').replace(/\r\n/g, '\n')
    : ''
  const lines = toLines(clean, stem)

  if (!stem) {
    return (
      <div className={className}>
        <ConceptExplanation lines={lines} hint={hint} score={score} showClosing={showClosing} />
      </div>
    )
  }

  const blocks = parseStem(lines)

  return (
    <div className={className}>
      <STEMExplanation
        blocks={blocks}
        rawLines={lines}
        hint={hint}
        score={score}
        showClosing={showClosing}
      />
    </div>
  )
}